### ISSUE TITLE
Incompatibilidad con Android nuevos

### ISSUE THREAD

**Issue by msevilla00** [Ibercivis/CitMApp#16]
Las últimas versiones de Android (al menos la 11) no permiten la instalación de la aplicación pues salta un mensaje de incompatibilidad por la versión del sistema operativo.

**Comment by Pablohn26** [comment]
![IMG_20231127_160900.jpg](https://github.com/Ibercivis/CitMApp/assets/1228418/180d61ed-e2ee-42da-b309-9c70da73c58e)

En mi dispositivo con Android 11 no funciona

**Comment by msevilla00** [comment]
Prueba a ver si con esta versión ya funciona: https://play.google.com/store/apps/details?id=com.ibercivis.mapp2

**Comment by msevilla00** [comment]
@frasanz: habría que unir ambas apps en Google Play o, en su caso, eliminar la vieja.
